/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export interface Exercise {
  _id: string
  _type: 'exercise'
  name: string
  description?: string
  difficulty: 'beginner' | 'intermediate' | 'advanced'
  image?: {
    _type: 'image'
    asset: {
      _ref: string
      _type: 'reference'
    }
    alt?: string
  }
  videoUrl?: string
  isActive?: boolean
}

export interface WorkoutSet {
  exercise: {
    _type: 'reference'
    _ref: string // Exercise document _id
  }
  reps: number
  weight?: number
  weightUnit: 'lbs' | 'kg'
}

export interface Workout {
  _id: string
  _type: 'workout'
  userId: string
  date: string // ISO string
  duration: number
  sets: WorkoutSet[]
}
